### ISSUE TITLE
tough-cookie-no-native issues

### ISSUE THREAD

**Issue by stevenvachon** [JonnyBurger/real-isomorphic-fetch#2]
I couldn't create an issue on its repo, so I've created it here.
- It should use [whatwg-url](https://npmjs.com/whatwg-url) instead of the browserify `url` package.
- It has `cheerio-without-node-native` package listed as a dependency, yet it is not used in any of its source code

**Comment by JonnyBurger** [comment]
Thanks for reporting this.
I've made it possible to file issues for `tough-cookie-no-native` now.

I removed the unnecessary dependency and pushed a new version: `2.4.0`.
Replacing the `url` straight up with `whatwg-url` breaks some of the unit tests though, so I am not confident enough to make this change.
